name: Construir App
on: [push]
jobs:
  construir:
    name: Construir App con Angular y NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configurar Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Genear archivo de configuracion de firebase
        working-directory: proyecto/src/environments
        run: echo -n -e "${{secrets.FIREBASE_CONFIG}}" > firebase.environment.ts

      - name: Instalar Dependencias
        working-directory: proyecto
        run: npm install

      - name: Ejecutar Pruebas de Unidad
        working-directory: proyecto
        run: npm run ci:test

      - name: Crear Build
        working-directory: proyecto
        run: npm run build

      - name: Deploy a firebase
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@v1.3.1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
          PROJECT_PATH: proyecto

      # - name: Notificar en Slack
      #   uses: rtCamp/action-slack-notify@v2.0.2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notificar exito en Slack
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: good
          SLACK_TITLE: Build Exitoso

      - name: Notificar error en Slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: danger
          SLACK_TITLE: Error en el build